name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN ||secrets.GITHUB_TOKEN }}
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install
        run: npm install --no-package-lock
      - name: Test
        run: npm test
        env:
          TEST_TELEGRAM_CHAT_ID: ${{ secrets.TEST_TELEGRAM_CHAT_ID }}
          TEST_SLACK_WEBHOOK: ${{ secrets.TEST_SLACK_WEBHOOK }}
          TEST_TWITTER_USER_ID: ${{ secrets.TEST_TWITTER_USER_ID }}
          TOM_EMAIL_PASSWORD: ${{ secrets.TOM_EMAIL_PASSWORD }}
          TOM_EMAIL_USER: ${{ secrets.TOM_EMAIL_USER }}
          TOM_STRIPE_KEY: ${{ secrets.TOM_STRIPE_KEY }}
          TOM_TELEGRAM_KEY: ${{ secrets.TOM_TELEGRAM_KEY }}
          TOM_TWITTER_ACCESS_TOKEN: ${{ secrets.TOM_TWITTER_ACCESS_TOKEN }}
          TOM_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TOM_TWITTER_ACCESS_TOKEN_SECRET }}
          TOM_TWITTER_CONSUMER_KEY: ${{ secrets.TOM_TWITTER_CONSUMER_KEY }}
          TOM_TWITTER_CONSUMER_SECRET: ${{ secrets.TOM_TWITTER_CONSUMER_SECRET }}
      - name: Release
        if: ${{ github.ref == 'refs/heads/master' && !startsWith(github.event.head_commit.message, 'chore(release):') && !startsWith(github.event.head_commit.message, 'docs:') }}
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          npm run release
